package = "FocksLang"
version = "0.1.0"
lua = ">=5.1"

[description]
summary = "A simple functional language"
maintainer = "Cootshk"
labels = [ "language", "functional" ]
license = "GPL-3.0"

[dependencies]
argparse = "0.7.1-1"
penlight = "1.14.0-3"
luastatic = "0.0.12-1"
# Add your dependencies here
# `busted = ">=2.0"`

[run]
args = [ "src/main.lua" ]

[build]
type = "builtin"

[source]
url = "https://github.com/cootshk/FocksLang"
